### ISSUE TITLE
Implement IFromDiscriminator interface (.NET 6+)

### ISSUE THREAD

**Issue by MihaMarkic** [microsoft/kiota-dotnet#232]
Models could implement an interface like this for .NET 6+:

```csharp
public interface IFromDiscriminator<T>
    where T: IParsable, IAdditionalDataHolder, new()
{
    static abstract T CreateFromDiscriminatorValue(IParseNode parseNode);
}
```

Then such methods are possible:

```csharp
public Task<T?> DeserializeAsync<T>(MemoryStream  stream, CancellationToken ct)
    where T : IFromDiscriminator<T>, IParsable, IAdditionalDataHolder, new()
{
    var pnf = ParseNodeFactoryRegistry.DefaultInstance;
    var root = await pnf.GetRootParseNodeAsync("application/json", stream);
    return root!.GetObjectValue<T>(T.CreateFromDiscriminatorValue);
}
```

**Comment by baywet** [comment]
We've considered that, a couple of challenges with that approach though:
- only available for dotnet from a design perspective
- would require us to drop netfx and netcore < 6 compatibility

Besides standardized/cleaner code, what other benefits do you think that would yield?

**Comment by baywet** [comment]
Sure, but it has a cost in terms of binary size at the end. And if it doesn't enable new scenarios, we're unlikely to accept such a change.
Doing some more research, I couldn't find a reference to that interface, Can you point to some documentation about it please?

**Comment by MihaMarkic** [comment]
Ah, that is just a sample interface I've crafted for demonstration (though it can be useful as it is). Sorry for not making it clearer. 
And I doubt that code will increase beyond a bunch of bytes.

**Comment by MihaMarkic** [comment]
The trick is with `static abstract` interface method [introduced](https://danielwoodward.dev/posts/csharp/csharp-11-static-abstract-members-in-interfaces) in C# 11/.NET 7 which allows static methods to be a part of the interface, in this case it's `static CreateFromDiscriminatorValue(...)` method.
(Actually, it was available in .NET6 through (.NET7) preview, hence a minimum is .NET7, not .NET6 as I wrote above.)

So, it's static, not instance, method provided through the interface. Does it explain it?

**Comment by baywet** [comment]
ah, I missed that detail, thanks for pointing this out.

What if we had instead

```csharp
public interface IFromDiscriminator<T>
    where T: IParsable
{
#if NET7_OR_GREATER
    static abstract T CreateFromDiscriminatorValue(IParseNode parseNode);
#endif
}
```
(note the removal of IAdditionalDataHolder as well)

This way we could add the interface declaration to all models, and it'd work in any context?

Technically we could even have a default implementation for all classes that don't have discriminated types like this, and omit generating generate the method with conditional directive, leading to smaller binary size for more modern applications.


```csharp
public interface IFromDiscriminator<T>
    where T: IParsable, new()
{
#if NET7_OR_GREATER
    static virtual T CreateFromDiscriminatorValue(IParseNode parseNode)
    {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new T();
    }
#endif
}
```

Which would lead to this in the models

```diff
+       #if NET7_OR_LOWER
        public static override User CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new User();
        }
+       #endif
```


Thoughts?

**Comment by MihaMarkic** [comment]
First solution - fine with me.
Second (static virtual) - yes, that would work as well (note - there is no `override` keyword in method implementation). Albeit there will be no code reduction, since you are still implementing CreateFromDiscriminatorValue methods on type (which is required if you want access them through type directly - SomeType.CreateFromDiscriminatorValue, AFAIK). But types without explicit implementation will certainly gain these.

**Comment by baywet** [comment]
> Albeit there will be no code reduction, since you are still implementing CreateFromDiscriminatorValue methods on type (which is required if you want access them through type directly - SomeType.CreateFromDiscriminatorValue, AFAIK). But types without explicit implementation will certainly gain these.

I'm a bit confused by this statement, where the second sentence seems to contradict the first one?

**Comment by MihaMarkic** [comment]
I meant that if you implement it like that, there would be no code reduction (assembly size would still be the same or a few bytes larger) though other types will gain the functionality. OTOH all other supported types gain CreateFromDiscriminatorValue though interface, so there is code reduction in that sense. Makes sense?

**Comment by baywet** [comment]
Thanks for clarifying! I'd understand that the method prototype still gets declared in every implementer (IL-wise), but don't you think we'll save at least the method body? (declared once instead of on every type)
