### ISSUE TITLE
Group kiota dotnet repositories

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-dotnet#238]
We initially made the choice to split the dotnet dependencies into multiple repositories to enable better isolation of concerns.
This has proven to represent mostly coordination overhead, without delivering much additional value (kiota-java and kiota-typescript being good examples of mono repos that work) as:

- clients regularly get dependencies misalignment issues, latest example: https://github.com/microsoft/kiota-http-dotnet/pull/257
- contributors need to coordinate between multiple repositories. see #225
- repos/pipeline maintenance and compliance gets multiplied by the number of repositories.
- we've reached the maximum number of repositories in GitHub projects, limiting our automation options.

Suggestion to move to a monorepo for dotnet dependencies and align the versions:
- [x] create a tests subdirectory here
- [x] create an abstractions subdirectory
- [x] move the test project to that subdirectory
- [x] update the sln reference
- [x] create an abstractions subdirectory under src
- [x] move the content in that sub directory
- [x] update the sln reference
- for reach other repo than abstractions:
    - [x] copy the src content to a subdirectory in src here
    - [x] copy the test content to a subdirectory in tests here
    - [x] update any abstractions reference to use a project reference instead of a package reference
    - [x] add reference to both projects in the sln
    - [x] merge the changelog information
    - [x] transfer the issues to this repository
    - [x] close the outstanding pull requests, leave a note to re-open on this repo instead
    - [x] update the readme to tell people the content has been moved
    - [x] archive the repository
    - [x] disable the ADO pipeline
- [x] update the workflows to build/test all projects
- [x] update the ADO pipeline to build/publish all packages
- [x] remove the version in the csproj, set them up so they use build props instead
- [x] add a build props, with the version set to the uppermost patch version
- [x] rename the repo to kiota-dotnet (and update the csproj repository reference)
- [ ] publish a new release

This will also unable the bundle package https://github.com/microsoft/kiota/issues/4636 work

**Comment by KennethHoff** [comment]
For clarity; this is referring to merging the _GitHub Repositories_, not the NuGet packages?

**Comment by baywet** [comment]
Correct

**Comment by pjmagee** [comment]
Mono repo is soooo much easier to deal with

**Comment by andrueastman** [comment]
Re-opening to close after task regarding migration of issues and and repo readmes are cleaned up.

**Comment by KennethHoff** [comment]
Will this repo be renamed to `kiota-dotnet` to follow the other runtimes/languages?
