### ISSUE TITLE
Date/Time serialization uses current culture

### ISSUE THREAD

**Issue by filipnavara** [microsoft/kiota-dotnet#280]
There are multiple calls to `DateTime.TryParse`, `DateTimeOffset.TryParse` and the respective `ToString` counterparts without a specified culture parameter. This implies a current culture is used instead of `CultureInfo.InvariantCulture` which would be an obvious choice for data interchange format.

Notably, the culture can use a non-Gregorian calendar, such as Persian one, which will likely result in incorrectly parsed/serialized data.

**Comment by baywet** [comment]
As a general rule of thumb, if issues are not assigned to anyone, nobody from our team is working on them (as in writing code to fix it, we might still be talking about it, etc...). We'll be more than happy to see a PR coming to address that.
