### ISSUE TITLE
Provide JsonConverter implementations

### ISSUE THREAD

**Issue by ajtribick** [microsoft/kiota-dotnet#282]
Kiota uses custom enum serialization that depends on the `EnumMemberAttribute`. Unfortunately the `JsonStringEnumConverter` provided in System.Text.Json does not use this attribute. In order to more easily integrate with non-Kiota uses of System.Text.Json, it would be useful to provide `JsonConverter`/`JsonConverterFactory` implementations that match the Kiota output.

Similarly the `Date` and `Time` types from Kiota abstractions also don't work directly with System.Text.Json.

**Comment by andrueastman** [comment]
Thanks for raising this @ajtribick 

At the moment, the library provides mechanisms for deserializing/serializing with the helper methods as documented at the link below. 

https://learn.microsoft.com/en-us/openapi/kiota/serialization?tabs=csharp#serialization-helpers

Any chance you can provide more information as to how the intergration with non Kiota uses would be hindered?
