### ISSUE TITLE
JsonSerializationWriter.WriteNonParsableObjectValue does not support anonymous objects

### ISSUE THREAD

**Issue by greg-ww** [microsoft/kiota-dotnet#306]
I was passing values into the AdditionalData property on the type generated in my Kiota client and I noticed that anonymous object values were being passed as empty objects.

```
{ "myAdditionalDataProperty": { } }
```

From debugging I can see that here https://github.com/microsoft/kiota-dotnet/blob/42ea74edf45d473462dd050661b1972ce14c15e1/src/serialization/json/JsonSerializationWriter.cs#L447 T comes through as "Object" so get properties returns no results. 

No error is thrown, the properties just never show up. It's possible this affects other types but I only tested with anonymous objects.

**Comment by greg-ww** [comment]
In trying to work around this issue, it seems the problem is worse than I thought.
I made a my own class for the data and that also failed to serialize properly, then I tried to use a Dictionary<string, object> and that didn't work either. 

The PR I submitted should work for custom non parseable classes but for dictionary should probably have it's own method. I will try to make a more extensive PR.

**Comment by baywet** [comment]
Hi @greg-ww 
Thanks for using kiota and for reaching out.
I have reviewed the PR *before* I saw this issue (orders of notifications on GitHub)
I'm curious to understand in what scenario do you feel like you need to rely on anonymous types?
For context, the serialization interface here was never meant to be used by humans, just to support the generated code.
Code that is generated from a schema, and should give us enough context not to have to rely on anonymous types.

**Comment by baywet** [comment]
Thanks for the additional context here.
Yes, it's a limitation today. https://github.com/microsoft/kiota/issues/62

**Comment by baywet** [comment]
Have you considered making the types that you pass as values of the additional properties implement IParsable instead?

**Comment by greg-ww** [comment]
> Have you considered making the types that you pass as values of the additional properties implement IParsable instead?

Yeah that's my next workaround, I only know I need to do that because I debugged into JsonSerializationWriter though. At minimum I'd expect an error if the types I tried to use are unsupported.

**Comment by baywet** [comment]
This is probably a good situation for other cases. Can you tweak this exception message as part of your PR please?
https://github.com/microsoft/kiota-dotnet/pull/307/files#diff-0f94b98a554904a6aea6e2d994e76fd110b76d2c96fd51d29e30ddad644ac620R552
