### ISSUE TITLE
Enable `nullable` context in all test projects.

### ISSUE THREAD

**Issue by andrueastman** [microsoft/kiota-dotnet#323]
Source of the project support NRT. However some of the test projects have this disabled. This should be aligned to clean up the code base.

Example at https://github.com/microsoft/kiota-dotnet/blob/8be19ce7ecaa92c001101f14e6acf6aecd57c47d/tests/abstractions/Microsoft.Kiota.Abstractions.Tests.csproj#L6

**Comment by bm0niz** [comment]
This will require changes in existing public APIs. Eg:

- Test => https://github.com/bm0niz/kiota-dotnet/blob/main/tests/http/httpClient/RequestAdapterTests.cs#L130
- API => https://github.com/bm0niz/kiota-dotnet/blob/main/src/abstractions/RequestInformation.cs#L152

Is it intended?

**Comment by baywet** [comment]
@bm0niz thanks for joining the discussion. 
No the intent is not to change the public API surface, especially for non test projects. 
The intent is to benefit from the latest language features in the test projects.

**Comment by bm0niz** [comment]
Thanks for your feedback @baywet.

Most of the NRT issues can be fixed easily. However when it comes to test classes implementing [this](https://github.com/microsoft/kiota-dotnet/blob/main/src/abstractions/serialization/IAdditionalDataHolder.cs#L18) interface is tough, and changing it for now I think it would be messy. The approach for these situations could be this:

```diff
public class MultipartSerializationWriterTests
{
    [Fact]
    public void ThrowsOnParsable()
    {
+      var nullJsonElement = JsonDocument.Parse("null").RootElement;
        
        // Arrange
        var testEntity = new TestEntity()
        {
            ...
            {
-              {"mobilePhone",null}, // write null value
+              {"mobilePhone",nullJsonElement}, // write null value
                {"accountEnabled",false}, // write bool value
                ...
            }
        };
        ...
    }
}
```

Let me know if that's OK and I can submit a PR so you guys can check.

**Comment by andrueastman** [comment]
I think this would work. Another alternative is to place the UntypedNull object in its place.

https://github.com/microsoft/kiota-dotnet/blob/main/src/abstractions/serialization/UntypedNull.cs

**Comment by baywet** [comment]
Exactly, please go ahead with the PR whenever you get time.
