### ISSUE TITLE
Extension methods for make serializing easier

### ISSUE THREAD

**Issue by svrooij** [microsoft/kiota-dotnet#338]
Create extension methods to make serializing easier discoverable, as suggested by @baywet

They have been removed from the PR, in this commit. Feel free to re-use https://github.com/svrooij/ms-kiota-dotnet/commit/a4a03d81e24d3c419792b383ba0db13484832fcb 

_Originally posted by @baywet in https://github.com/microsoft/kiota-dotnet/pull/311#discussion_r1721782809_

**Comment by baywet** [comment]
Hi @svrooij 
Thanks for creating this issue. Let's talk about the experience first so we can later on decide on solutions.

I'm guessing we'd want the following:


```csharp
IParsable myModel = new();
await myModel.SerializeAsync("mediaType", stream);
var result = await myModel.SerializeAsStringAsync("mediaType");

await myModel.SerializeToJsonAsync(stream);
var result = await myModel.SerializeToJsonAsStringAsync();
```

This should work for `Parsable[]` and `IEnumerable<IParsable>` as well.

To avoid any confusion, it should be in a sub-namespace.

In terms of parameters, here is what the method with the most parameters would look like, everything else will be a subset.

```csharp
public static async Task SerializeAsync<T>(this T parsable, string meditaType, Stream targetStream, CancellationToken cancellationToken = default) where T : IParsable {
//
}
```

Did I miss anything? Also CC @andrueastman

**Comment by svrooij** [comment]
Not to forget IEnumerable<T> and T[]

But looks good too me

**Comment by svrooij** [comment]
@baywet to allow discoverability I'm suggesting the following, what do you think:

- Add those extension methods to the same namespace as the `IParsable`, this will help with discoverability (which is what we all want I guess)
- Add them to a different namespace, and maybe point them to it with xml docs on the `IParsable`

But I would suggest to add the extension methods to the dedicated project. That means you won't have a `SerializeToJsonAsStringAsync` if you did not include the json package. And I guess everybody is using the json package, but we are not using the forms stuff so those are removed when we generate the kiota client. Then having a `SerializeToFormUrlEncoded` would be weird to have in `Abstractions`

**Comment by baywet** [comment]
Something like this?

| method name | package | namespace |
|---------|-----------|----------|
| SerializeAsStringAsync | abstractions | Microsoft.Kiota.Serialization |
| SerializeToJsonAsStringAsync | serialization json | Microsoft.Kiota.Serialization.Json |

???
