### ISSUE TITLE
Allow fallback for unhandled non-success status codes

### ISSUE THREAD

**Issue by IanKemp** [microsoft/kiota-dotnet#340]
### Is your feature request related to a problem? Please describe the problem.

Related to microsoft/kiota#3744 which was never satisfactorily addressed. The problem is pretty simple:

* An endpoint's API specification says it supports 400 as a response, but it can actually return 404 as well
* Kiota client generated against that endpoint
* Generated client is invoked in such a way that causes the endpoint to return undocumented 404
* Kiota throws an incredibly unhelpful `The server returned an unexpected status code and no error factory is registered for this code` exception

Now, I know the maintainers are gonna point me to [this](https://learn.microsoft.com/en/openapi/kiota/errors#solutions-to-missing-error-mappings), but it doesn't cover a specific scenario: **allowing me to see the returned 404 response** so that I can either tell the API owner about it so that they fix their spec (because if you've ever worked with "enterprise" companies you know that they require evidence for _everything_), or fix up my local copy of their spec.

Using a `DelegatingHandler` to throw/log on any unsuccessful responses (`HttpResponseMessage.IsSuccessStatusCode == false`) isn't an option because in the given example, [it will _also_ throw/log for the 400 case](https://github.com/microsoft/kiota/issues/3744#issuecomment-2119763622) - which it shouldn't, because that's covered by a generated error handler.

There is a `Action<RequestConfiguration<T>>` parameter that can be supplied to every Kiota-generated method, and it's possible to specify an `IResponseHandler` there that can _maybe_ do what is requested here, but (a) this is on a per-method basis and not a global option (b) as noted [here](https://github.com/microsoft/kiota/issues/3744#issuecomment-1818015197), that `IResponseHandler` isn't in addition to the default Kiota handling but a _replacement_ of it; which rather defeats the point.

### Client library/SDK language

None

### Describe the solution you'd like

Any unsuccessful HTTP response (that is, one where `HttpResponseMessage.IsSuccessStatusCode` is `false`) will filter through that endpoint's explicit error mappings, exactly as currently.

However, in the case that no mapping is found for the returned status code, the library will attempt to resolve an implementation of the below interface:

```csharp
public interface IUnsuccessfulResponseFallbackHandler
{
    Task HandleAsync(HttpResponseMessage response, CancellationToken cancellationToken = default);
}
```

If such an implementation is found, the problematic `HttpResponseMessage` is passed to this implementation's `HandleAsync` method. After this, Kiota will continue to behave as currently, i.e. throw `The server returned an unexpected status code and no error factory is registered for this code`.

In essence, this is inserting a step between the current "look up error mapping for this unsuccessful status code" and "throw if no matching error mapping is found". Because of the way that `HttpClientRequestAdapter` is currently designed, specifically the `ThrowIfFailedResponse` method, actually implementing this is not simple.

### Additional context

* This is a proposal/RFC, not a fully-fleshed-out "I have the code in a feature branch". I don't know the full implications of implementing this, I don't know what shape the contract should be (could we somehow just use a `DelegatingHandler` instead of a whole new interface? maybe? IDK), I don't know how this interface would be provided (a new `IRequestOption` implementation?), ...
* The interface I've defined cannot affect the flow of response processing; this is by design to keep this proposal as simple as possible. (Sure, you can read to the end of the response content stream and not rewind it and thus cause Kiota to blow up internally when _it_ tries to access that stream, but that's true of `DelegatingHandler`s anyway IIRC... if you want to shoot yourself in the foot, I ain't gonna stop you.)

**Comment by kieronlanning** [comment]
Did anything ever happen with this?

**Comment by baywet** [comment]
@kieronlanning nothing. I re-closed the issue as not planned to clearly communicate that.
Let us know if you have any additional comments or questions.

**Comment by kieronlanning** [comment]
Thanks @baywet.

I have the same issue as the original author I believe: an upstream Open-API that I'm not in control of has undocumented response codes/ error conditions.

In this case it's returning an undocumented 400 - but I can't seem to get to the payload to understand what the problem is.

**Comment by baywet** [comment]
Since this issue was created, we added support for response body inspection.
See #482 and associated items.
Let us know if you have any additional comments or questions.

**Comment by kieronlanning** [comment]
Looking through the GH issue, look me to this [page](https://learn.microsoft.com/en-us/openapi/kiota/middleware?tabs=csharp#middleware-handlers), where it details what support there is for body inspector.

It looks as though there is no support for C#, is that correct?

**Comment by baywet** [comment]
Thanks for the callout, with the break, we forgot to merge a pull request https://github.com/MicrosoftDocs/openapi-docs/pull/140

**Comment by baywet** [comment]
One is scheduled for tomorrow, but why would you expect a new release? The inspection handler is already available in the kiota dotnet dependencies.

**Comment by kieronlanning** [comment]
Oh, it just the documentation that was out of out not the generator itself. Understood.
