### ISSUE TITLE
CancellationToken is required to serialize?

### ISSUE THREAD

**Issue by OlavBjorndal** [microsoft/kiota-dotnet#366]
Hi, 

mabye there is something that i haven't been able to grasp yet, and I'm fairly new to kiota. 
But during my nuget update of GraphSDK i met this errorMessage:
![image](https://github.com/user-attachments/assets/be7d2ca2-9b36-495b-a29f-8bd96dc96723)

I see the previous version of graphSDK I used had kiota-serialization-json-dotnet 1.3.3, but now with the monorepo im trying to use 1.12.2.

I'm just wondering if I'm doing something wrong, if this is intensionally or just a small bug?

**Comment by baywet** [comment]
Hi @OlavBjorndal 
Thank you for using kiota and for reaching out.

I think this got lost in the multiple reviews of #311.
I have just authored a pull request to make the parameter optional again and fix a few other alignment issues #367

Let us know if you have any additional comments or questions.
