### ISSUE TITLE
prepare for std uri template 2 and date time drop

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-dotnet#395]
related https://github.com/std-uritemplate/std-uritemplate-csharp/pull/11
The following types need to the normalized to their RFC3339 representation before they are passed to std URI template when they are present are query or path parameter values
DateTime, DateTimeOffset, and their collection representations (array, enumerable)

**Comment by andrueastman** [comment]
I believe this is already handled in the library. 

The request info class looks to handle the types already here
https://github.com/microsoft/kiota-dotnet/blob/ae93dbc61908d8048a92cecf13564be2782685d0/src/abstractions/RequestInformation.cs#L127

Furthermore, validation checks are passing as the tests below are part of the suite.
- https://github.com/microsoft/kiota-dotnet/blob/ae93dbc61908d8048a92cecf13564be2782685d0/tests/abstractions/RequestInformationTests.cs#L155
- https://github.com/microsoft/kiota-dotnet/blob/ae93dbc61908d8048a92cecf13564be2782685d0/tests/abstractions/RequestInformationTests.cs#L647
- https://github.com/microsoft/kiota-dotnet/blob/ae93dbc61908d8048a92cecf13564be2782685d0/tests/abstractions/RequestInformationTests.cs#L665
