### ISSUE TITLE
Add support for Basic Authentication

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-dotnet#472]
The API which i am using Kiota to generate a client for uses Basic auth however there is no included provider to implement basic auth, which is a common and wide spread provider.

As such it would be useful if this was provided as part of the base package.

**Comment by baywet** [comment]
Hi @thompson-tomo 
Thank you for using kiota and for reaching out.

Kiota technically already supports it through the [ApiKeyAuthenticationProvider](https://github.com/microsoft/kiota-dotnet/blob/c6f3ceb91d677baba159dbe6eaff75d48ab5fff5/src/abstractions/authentication/ApiKeyAuthenticationProvider.cs#L30)

Setting an API key of "Basic base64(username:password)", parameter name of "Authorization" and location of Header would do the trick.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#examples

Of course, we could always provide a derived class that does the setup for the developer to make it easier and more obvious.

Is this something you'd like to submit a pull request for provided some guidance?

**Comment by thompson-tomo** [comment]
Sure I will put a pr through.
